version: '3.8'

services:
  web:
    image: us-central1-docker.pkg.dev/folio-app-492702/folio-repo/web:latest
    ports:
      - "3000:3000"
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - MUSIC_KIT_TOKEN=${MUSIC_KIT_TOKEN}
    # GCP Cloud Run Extensions
    x-google-cloud-run:
      min-instances: 0
      execution-environment: gen2

  image-proc:
    image: imgproxy/imgproxy:latest
    ports:
      - "8080:8080"
    environment:
      - IMGPROXY_LISTEN=:8080
      - IMGPROXY_MAX_SRC_RESOLUTION=50
