export const APP_LIMITS = {
  FREE: {
    MAX_FOLIOS: 10,
    MAX_POSTCARDS: 100,
    MAX_PHOTOS_PER_POSTCARD: 5,
    MAX_PHOTOS_PER_COLLECTION: 20,
  },
  PREMIUM: {
    MAX_FOLIOS: 100,
    MAX_POSTCARDS: 1000,
    MAX_PHOTOS_PER_POSTCARD: 20,
    MAX_PHOTOS_PER_COLLECTION: 100,
  },
  ADMIN: {
    MAX_FOLIOS: Infinity,
    MAX_POSTCARDS: Infinity,
    MAX_PHOTOS_PER_POSTCARD: 10,
    MAX_PHOTOS_PER_COLLECTION: 50,
  }
};

export const SUPPORT_URL = "https://buymeacoffee.com/h9aq9muuYz";
